### PR TITLE
Add support for storing log files in specified path in bucket

### PR DESCRIPTION
**Pull request by qrczak0**
I'm missing possibility to store log files in specified path not only on root folder.
With this tweak you can pass "path" attribute as "my/container/log.txt" and log files will be saved in  "my/container/*" instead bucket root folder.

### CODE REVIEW

**Comment by SeppPenner** [comment]
Just one question (I haven't tried this yet): When you use the sink like this:

```csharp
var logger = new LoggerConfiguration().WriteTo
    .AmazonS3(
        "awsSubPath/log.txt",
        "mytestbucket-aws",
        Amazon.RegionEndpoint.EUWest2,
        "ABCDEFGHIJKLMNOP",
        "c3fghsrgwegfn://asdfsdfsdgfsdg"
    )
    .CreateLogger();
```
, your changes will make it possible to log to e.g. `mytestbucket-aws/awsSubPath/log.txt` on S3 (as if S3 was a **regular** file system), correct?

So, the difference is now, that https://github.com/SeppPenner/Serilog.Sinks.AmazonS3/blob/master/HowToUse.md#configuration-options --> `path` can be not only a file, but a subfolder path?

**Comment by qrczak0** [comment]
Exactly as you described. After some testing I'm missing one more thing. When you set path with subfolder, then log file created on local machine is stored in same subfolder in application working directory and stores log files there. For example for path `awsSubPath/log.txt` and application run in `C:\MyApplication` files are stored locally in `C:\MyApplication\awsSubPath\log.txt` and on S3 `mytestbucket-aws/awsSubPath/log.txt`

I think it would be awesome to have possibility to configure separate path for files stored locally and separate for S3 bucket path.

**Comment by SeppPenner** [comment]
@qrczak0 Yep, that was exactly what I was thinking. Your new changes look better for this scenario. I'm not sure yet when I will be able to merge it and make a new version. I hope tomorrow.

**Comment by qrczak0** [comment]
I have updated my PR and decided to add new parameter "bucketPath" and there it is possible to define where files will be stored on Amazon S3 bucket. Path for local files will stay as it was before.

**Comment by SeppPenner** [comment]
I will have to change this to have a default value of `string.Empty` because `null` crashes the line:

```csharp
Key = Path.Combine(this.pathRoller.LogFileBucketPath,
    Path.GetFileName(this.currentFileName)).Replace("\\", "/")
```

**Comment by SeppPenner** [comment]
This is now added in the version 1.0.5.

**Comment by qrczak0** [comment]
Great, thanks :)

**Comment by qrczak0** [comment]
Something is wrong with dependant AWS packages
https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.Serilog.Sinks.AmazonS3/
`AWSSDK.Core (>= 3.3.109)`
where for `AWSSDK.Core` newest version is `3.3.104` (https://www.nuget.org/packages/AWSSDK.Core)

**Comment by SeppPenner** [comment]
Yeah, I have seen that... I will provide a new package soon...

**Comment by SeppPenner** [comment]
I have created a seperate issue to avoid duplicates (Others might find this issue as well).

**Comment by SeppPenner** [comment]
Is fixed with https://github.com/SeppPenner/Serilog.Sinks.AmazonS3/commit/554de96d7308bea2277e36b9692c34df1955fb51 in version 1.0.6.

**Pull request merged**
