### PR TITLE
Add new constructor taking serviceUrl instead of Endpoint

### PR DESCRIPTION
**Pull request by Galouw**
For enterprise usage it should be possible to specify service url instead of endpoint
This pull request adds a constructor taking the service url in parameter.

### CODE REVIEW

**Comment by SeppPenner** [comment]
Looks good. I will update the changelog and the description and release a new nuget package soon.

**Comment by SeppPenner** [comment]
By the way, do you have an example for a serviceUrl? I just didn't find anything I can put into the documentation at the moment...

**Comment by Galouw** [comment]
"s3.amazonaws.com" is the serviceUrl for the standard endpoint.
I initially found this parameter here: https://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/T_Amazon_S3_AmazonS3Config.htm

**Comment by SeppPenner** [comment]
Ok, thank you. I have updated the documentation (How to use file) and added this service URL as default. I already found this Amazon S3 page but didn't see the default value anywhere...

**Pull request merged**
