### PR TITLE
added support for DisablePayloadSigning to disables the Amazon S3 SigV4 payload 

### PR DESCRIPTION
**Pull request by jawand**
added support for DisablePayloadSigning to disables the Amazon S3 SigV4 payload signing data integrity check on upload request, since cloudflare R2 does not work with SigV4 yet.

#55

### CODE REVIEW

**Comment by jawand** [comment]
@SeppPenner can you please check this and let me know your thoughts. I personally need this option to use Cloudflare R2 as they have S3 API compatibility but lack SigV4 implementation.

**Review by SeppPenner — APPROVED** [review]

**Comment by SeppPenner** [comment]
Fixes https://github.com/serilog-contrib/Serilog.Sinks.AmazonS3/issues/55.

**Comment by SeppPenner** [comment]
I hope to bring out a new version soon.

**Comment by SeppPenner** [comment]
New release is out, NuGet package should be available soon :)

**Comment by jawand** [comment]
@SeppPenner Thanks a lot :)

**Pull request merged**
